// src/app/feeds/feed/feed.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { ActivatedRoute } from '@angular/router';
import { ViewportScroller } from '@angular/common';

import { HackerNewsAPIService } from '../../shared/services/hackernews-api.service';
import { Story } from '../../shared/models/story';

@Component({
  selector: 'app-feed',
  standalone: false,
  templateUrl: './feed.component.html',
  styleUrls: ['./feed.component.scss']
})
export class FeedComponent implements OnInit, OnDestroy {
  typeSub!: Subscription;
  pageSub!: Subscription;
  items!: Story[];
  feedType = '';
  pageNum = 1;
  listStart = 1;
  errorMessage = '';

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private route: ActivatedRoute,
    private viewportScroller: ViewportScroller
  ) {}

  ngOnInit(): void {
    this.typeSub = this.route
      .data
      .subscribe(data => {
        this.feedType = data['feedType'];
      });

    this.pageSub = this.route.params.subscribe(params => {
      this.pageNum = params['page'] ? +params['page'] : 1;
      this._hackerNewsAPIService.fetchFeed(this.feedType, this.pageNum)
        .subscribe({
          next: items => this.items = items,
          error: () => this.errorMessage = 'Could not load ' + this.feedType + ' stories.',
          complete: () => {
            this.listStart = ((this.pageNum - 1) * 30) + 1;
            this.viewportScroller.scrollToPosition([0, 0]);
          }
        });
    });
  }

  ngOnDestroy(): void {
    this.typeSub.unsubscribe();
    this.pageSub.unsubscribe();
  }

  trackById(_index: number, item: Story): number {
    return item.id;
  }
}

<div class="main-content">
  <app-loader *ngIf="!items && !errorMessage"></app-loader>
  <app-error-message [message]="errorMessage" *ngIf="!items && errorMessage !==''"></app-error-message>

  <div *ngIf="items">
    <p class="job-header" *ngIf="feedType === 'jobs'">
      These are jobs at startups that were funded by Y Combinator.
      You can also get a job at a YC startup through <a href="https://triplebyte.com/?ref=yc_jobs">Triplebyte</a>.
    </p>
    <ol *ngIf="feedType !== 'new'" [class.list-margin]="feedType !== 'jobs'" start="{{ listStart }}">
      <li *ngFor="let item of items; trackBy: trackById" class="post">
        <item class="item-block" [item]="item"></item>
      </li>
    </ol>
    <div class="nav">
      <a *ngIf="listStart !== 1" [routerLink]="['/' + feedType, pageNum - 1]" routerLinkActive="active" class="prev">
        ‹ Prev
      </a>
      <a *ngIf="items.length === 30" [routerLink]="['/' + feedType, pageNum + 1]" routerLinkActive="active" class="more">
        More ›
      </a>
    </div>
  </div>
</div>

// src/components/feeds/Feed.tsx
import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Story } from '../../models/story';
import { fetchFeed } from '../../services/hackernews-api';
import Loader from '../shared/Loader';
import ErrorMessage from '../shared/ErrorMessage';
import Item from './Item';
import './Feed.scss';

interface FeedProps {
    feedType: string;
}

export default function Feed({ feedType }: FeedProps) {
    const { page } = useParams<{ page: string }>();
    const pageNum = page ? parseInt(page, 10) : 1;
    const [items, setItems] = useState<Story[] | null>(null);
    const [errorMessage, setErrorMessage] = useState('');

    const listStart = (pageNum - 1) * 30 + 1;

    useEffect(() => {
        setItems(null);
        setErrorMessage('');

        fetchFeed(feedType, pageNum)
            .then((data) => {
                setItems(data);
                window.scrollTo(0, 0);
            })
            .catch(() => {
                setErrorMessage('Could not load ' + feedType + ' stories.');
            });
    }, [feedType, pageNum]);

    return (
        <div className="main-content">
            {!items && !errorMessage && <Loader />}
            {!items && errorMessage !== '' && <ErrorMessage message={errorMessage} />}

            {items && (
                <div>
                    {feedType === 'jobs' && (
                        <p className="job-header">
                            These are jobs at startups that were funded by Y Combinator.
                            You can also get a job at a YC startup through <a href="https://triplebyte.com/?ref=yc_jobs">Triplebyte</a>.
                        </p>
                    )}
                    {feedType !== 'new' && (
                        <ol className={feedType !== 'jobs' ? 'list-margin' : undefined} start={listStart}>
                            {items.map((item) => (
                                <li key={item.id} className="post">
                                    <Item item={item} />
                                </li>
                            ))}
                        </ol>
                    )}
                    <div className="nav">
                        {listStart !== 1 && (
                            <Link to={'/' + feedType + '/' + (pageNum - 1)} className="prev">
                                &#8249; Prev
                            </Link>
                        )}
                        {items.length === 30 && (
                            <Link to={'/' + feedType + '/' + (pageNum + 1)} className="more">
                                More &#8250;
                            </Link>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
