// src/pages/Feed/Feed.tsx
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import type { FeedName } from '../../models/feed-type.type';
import type { Story } from '../../models/story';
import { fetchFeed } from '../../services/hackernews-api';
import { Loader } from '../../components/Loader/Loader';
import { ErrorMessage } from '../../components/ErrorMessage/ErrorMessage';
import { Item } from '../../components/Item/Item';
import './feed.scss';

export function Feed({ feedType }: { feedType: FeedName }) {
  const page = Number(useParams().page ?? 1);
  const [items, setItems] = useState<Story[] | undefined>();
  const [errorMessage, setErrorMessage] = useState('');
  const listStart = (page - 1) * 30 + 1;
  useEffect(() => {
    let cancelled = false;
    setItems(undefined);
    setErrorMessage('');
    fetchFeed(feedType, page)
      .then((result) => {
        if (!cancelled) {
          setItems(result);
          window.scrollTo(0, 0);
        }
      })
      .catch(() => {
        if (!cancelled) setErrorMessage(`Could not load ${feedType} stories.`);
      });
    return () => {
      cancelled = true;
    };
  }, [feedType, page]);
  return (
    <div className="app-feed">
      <div className="main-content">
        {!items && !errorMessage && <Loader />}
        {!items && errorMessage && <ErrorMessage message={errorMessage} />}
        {items && (
          <>
            {feedType === 'jobs' && (
              <p className="job-header">
                These are jobs at startups that were funded by Y Combinator. You can also get a job at a YC startup
                through <a href="https://triplebyte.com/?ref=yc_jobs">Triplebyte</a>.
              </p>
            )}
            <ol className={feedType !== 'jobs' ? 'list-margin' : undefined} start={listStart}>
              {items.map((item) => (
                <li className="post" key={item.id}>
                  <Item item={item} />
                </li>
              ))}
            </ol>
            <div className="nav">
              {listStart !== 1 && (
                <Link to={`/${feedType}/${page - 1}`} className="prev">
                  ‹ Prev
                </Link>
              )}
              {items.length === 30 && (
                <Link to={`/${feedType}/${page + 1}`} className="more">
                  More ›
                </Link>
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// src/app/feeds/feed/feed.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { ActivatedRoute } from '@angular/router';
import { ViewportScroller } from '@angular/common';

import { HackerNewsAPIService } from '../../shared/services/hackernews-api.service';
import { Story } from '../../shared/models/story';

@Component({
  selector: 'app-feed',
  standalone: false,
  templateUrl: './feed.component.html',
  styleUrls: ['./feed.component.scss']
})
export class FeedComponent implements OnInit, OnDestroy {
  typeSub!: Subscription;
  pageSub!: Subscription;
  items!: Story[];
  feedType = '';
  pageNum = 1;
  listStart = 1;
  errorMessage = '';

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private route: ActivatedRoute,
    private viewportScroller: ViewportScroller
  ) {}

  ngOnInit(): void {
    this.typeSub = this.route
      .data
      .subscribe(data => {
        this.feedType = data['feedType'];
      });

    this.pageSub = this.route.params.subscribe(params => {
      this.pageNum = params['page'] ? +params['page'] : 1;
      this._hackerNewsAPIService.fetchFeed(this.feedType, this.pageNum)
        .subscribe({
          next: items => this.items = items,
          error: () => this.errorMessage = 'Could not load ' + this.feedType + ' stories.',
          complete: () => {
            this.listStart = ((this.pageNum - 1) * 30) + 1;
            this.viewportScroller.scrollToPosition([0, 0]);
          }
        });
    });
  }

  ngOnDestroy(): void {
    this.typeSub.unsubscribe();
    this.pageSub.unsubscribe();
  }

  trackById(_index: number, item: Story): number {
    return item.id;
  }
}

<div class="main-content">
  <app-loader *ngIf="!items && !errorMessage"></app-loader>
  <app-error-message [message]="errorMessage" *ngIf="!items && errorMessage !==''"></app-error-message>

  <div *ngIf="items">
    <p class="job-header" *ngIf="feedType === 'jobs'">
      These are jobs at startups that were funded by Y Combinator.
      You can also get a job at a YC startup through <a href="https://triplebyte.com/?ref=yc_jobs">Triplebyte</a>.
    </p>
    <ol *ngIf="feedType !== 'new'" [class.list-margin]="feedType !== 'jobs'" start="{{ listStart }}">
      <li *ngFor="let item of items; trackBy: trackById" class="post">
        <item class="item-block" [item]="item"></item>
      </li>
    </ol>
    <div class="nav">
      <a *ngIf="listStart !== 1" [routerLink]="['/' + feedType, pageNum - 1]" routerLinkActive="active" class="prev">
        ‹ Prev
      </a>
      <a *ngIf="items.length === 30" [routerLink]="['/' + feedType, pageNum + 1]" routerLinkActive="active" class="more">
        More ›
      </a>
    </div>
  </div>
</div>
